### ISSUE TITLE
Fix Display Owner Error 

### ISSUE THREAD

**Issue by GhazalKazemi** [GhazalKazemi/pet-clinic#62]

**Comment by GhazalKazemi** [comment]
Caused by: org.attoparser.ParseException: Exception evaluating SpringEL expression: "telephone" (template: "owner/ownerDetails" - line 27, col 13)
	at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:393)
	at org.attoparser.MarkupParser.parse(MarkupParser.java:257)
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:230)
	... 55 more
